### ISSUE TITLE
Conversion to other platform

### ISSUE THREAD

**Issue by kissievendor** [TJKlein/DeepNAT#6]
Hi,
I am curious to see if I can make the code work for my research.
However I had problems installing Caffe. 
Do you have the code in Keras, Tensorflow or anything? Or can you convert the .caffemodel files?

Thanks. 
Kirsten

**Comment by TJKlein** [comment]
Hi Kirsten,
the code is quite old. Probably, it is quicker to implement it from scratch in Pytorch/Keras etc. as all these new frameworks already have 3D convolutions.
You might also want to take look at [QuickNAT](https://github.com/ai-med/quickNAT_pytorch), which is sort of an improvement over DeepNAT.
Cheers,
Tassilo

**Comment by kissievendor** [comment]
Thanks for the quick reply! I will look into it.
